<?php
namespace Application\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Application\Entity\Account;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRepository extends EntityRepository
{

    public function createAccount($data)
    {
        $em = $this->getEntityManager();
        $accountEntity = new Account();
        $accountEntity->setUsername($data['username'])
                      ->setPassword($data['password'])
                      ->setLastLoggedInDtTm(new \DateTime())
                      ->setCreateDtTm(new \DateTime());
                       
        $em->persist($accountEntity);
        $em->flush();
       
        return $accountEntity;
    }
    
}
