<?php

namespace Application\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManagerInterface;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUsers()
    { 
        
        $em = $this->getEntityManager();
        $conn = $em->getConnection();
        $query = "Select * from user";
        $statement = $conn->executeQuery($query);
        
        $userList = $statement->fetchAll();
        return $userList;
    }
}
