<?php
namespace Application\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManagerInterface;
use Application\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function getUsers()
    {
        $em = $this->getEntityManager();
        $conn = $em->getConnection();
        $query = "Select * from user";
        $statement = $conn->executeQuery($query);
        
        $userList = $statement->fetchAll();
        return $userList;
    }

    public function createUser($accountObj, $data)
    {
        $em = $this->getEntityManager();
        
        $user = new User();
        $user->setAccount($accountObj)
            ->setFirstName($data['first_name'])
            ->setLastName($data['last_name'])
            ->setEmail($data['email'])
            ->setCreateDtTm(new \DateTime())
            ->setUpdateDtTm(new \DateTime());
        
        $em->persist($user);
        $em->flush();
    }
}
